server:
  port: 8765
spring:
  application:
    name: gateway
  cloud:
    gateway:
      #      routes:
      #        - id: shop
      #          uri: http://localhost:8080/  # Базовый адрес для shop
      #          predicates:
      #            - Path=/shop/**
      ##          filters:
      ##            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka